# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [44]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
# Import API key
from api_keys import g_key
import time

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [45]:
file_to_load = ("City_data.csv")
cities_data = pd.read_csv(file_to_load, sep = ',')
df=pd.DataFrame(cities_data)
df.head(50)

,City,Latitude,Longitude,Max_Temp,Humidity,Wind_Speed,Cloudiness,Date,Country
0,Tokyo,35.6895,139.6917,65.44,43,8.01,20,1635470149,JP
1,Jakarta,-6.2146,106.8451,83.52,78,5.75,100,1635470411,ID
2,Delhi,28.6667,77.2167,62.69,88,0.00,0,1635470179,IN
3,Mumbai,19.0144,72.8479,78.78,44,4.61,40,1635470303,IN
4,Manila,14.6042,120.9822,87.13,59,7.00,20,1635470220,PH
5,Shanghai,31.2222,121.4581,67.87,62,6.71,0,1635470376,CN
6,São Paulo,-23.5475,-46.6361,67.44,84,8.05,75,1635470380,BR
7,Seoul,37.5683,126.9778,60.37,48,8.05,0,1635470357,KR
8,Mexico City,19.4285,-99.1277,64.11,66,11.01,90,1635470410,MX
9,Guangzhou,23.1167,113.2500,75.99,59,5.99,3,1635470346,CN
10,Beijing,39.9075,116.3972,53.49,42,3.47,5,1635470358,CN
11,Cairo,30.0626,31.2497,72.36,44,5.75,73,1635470436,EG
12,New York,40.7143,-74.0060,56.30,72,1.99,90,1635470257,US
13,Moscow,55.7522,37.6156,45.23,78,3.18,100,1635470230,RU
14,Bangkok,13.7500,100.5167,78.91,90,4.25,100,1635470441,TH
15,Buenos Aires,-34.6132,-58.3772,78.48,73,11.50,0,1635470240,AR
16,Shenzhen,22.5455,114.0683,79.14,81,6.82,71,1635470443,CN
17,Dhaka,23.7104,90.4074,78.78,83,0.00,40,1635470306,BD
18,Lagos,6.5833,3.7500,77.32,92,1.77,100,1635470446,NG
19,Istanbul,41.0351,28.9833,57.06,67,11.50,20,1635470169,TR
20,Ōsaka,34.6937,135.5022,67.05,45,14.97,75,1635470448,JP
21,Karachi,24.9056,67.0822,66.02,72,0.00,2,1635470338,PK
22,Bangalore,12.9762,77.6033,69.62,94,0.00,75,1635470408,IN
23,Tehran,35.6944,51.4215,51.78,46,0.00,75,1635470398,IR
24,Kinshasa,-4.3246,15.3215,79.12,83,6.91,20,1635470453,CD
25,Ho Chi Minh City,10.7500,106.6667,84.22,79,3.44,40,1635470183,VN
26,Los Angeles,34.0522,-118.2437,88.21,37,3.44,1,1635470353,US
27,Rio de Janeiro,-22.9028,-43.2075,73.90,96,5.75,90,1635470166,BR
28,Nanyang,32.9947,112.5328,61.38,63,2.68,100,1635470457,CN
29,Baoding,38.8511,115.4903,56.93,51,4.07,7,1635470459,CN
30,Chennai,13.0878,80.2785,78.78,89,2.30,40,1635470460,IN
31,Chengdu,30.6667,104.0667,60.69,77,0.00,40,1635470462,CN
32,Lahore,31.5497,74.3436,62.58,82,3.44,0,1635470403,PK
33,Paris,48.8534,2.3488,53.19,85,1.01,0,1635470280,FR
34,London,51.5085,-0.1257,59.38,82,6.91,100,1635470460,GB
35,Linyi,35.0631,118.3428,59.31,50,3.24,35,1635470174,CN
36,Tianjin,39.1422,117.1767,55.35,82,2.24,27,1635470467,CN
37,Shijiazhuang,38.0414,114.4786,55.26,53,0.98,100,1635470469,CN
38,Zhoukou,33.6333,114.6333,63.77,59,4.70,100,1635470470,CN
39,Lima,-12.0432,-77.0282,64.90,77,14.97,75,1635470288,PE
40,Hyderābād,25.3924,68.3737,76.37,28,3.96,0,1635470473,PK
41,Handan,36.6006,114.4678,59.92,64,3.74,69,1635470474,CN
42,Bogotá,4.6097,-74.0817,54.91,94,3.44,75,1635470379,CO
43,Weifang,36.7100,119.1019,61.70,50,4.81,12,1635470300,CN
44,Nagoya,35.1815,136.9064,64.20,42,9.42,0,1635470478,JP
45,Wuhan,30.5833,114.2667,64.49,56,4.36,69,1635470479,CN
46,Heze,35.2431,115.4411,62.04,62,6.38,80,1635470480,CN
47,Ganzhou,28.8184,115.4327,66.97,63,4.27,97,1635470316,CN
48,Tongshan,34.1805,117.1571,61.50,54,4.83,8,1635470483,CN
49,Chicago,41.8500,-87.6500,55.83,92,13.80,90,1635470298,US

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [46]:
gmaps.configure(api_key=g_key)

In [48]:
fig = gmaps.figure(center=(0,0),zoom_level=2)
heatmap_layer =gmaps.heatmap_layer(df[['Latitude','Longitude']],weights= df['Humidity'],max_intensity=100, point_radius=6.0)
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [49]:
len(df)

619

In [50]:
df = df.dropna(how='any')
len(df)

619

In [51]:
#A max temperature lower than 80 degrees but higher than 70.
#Wind speed less than 10 mph.
#Zero cloudiness.
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

idealCity=df.loc[(df['Max_Temp']<=80) & (df['Max_Temp']>=70)]
idealCity=idealCity.loc[(idealCity['Wind_Speed']<=10)]
idealCity=idealCity.loc[(idealCity['Cloudiness']==0)]
idealCity

,City,Latitude,Longitude,Max_Temp,Humidity,Wind_Speed,Cloudiness,Date,Country
40,Hyderābād,25.3924,68.3737,76.37,28,3.96,0,1635470473,PK
139,Belo Horizonte,-19.9208,-43.9378,74.75,50,6.91,0,1635470370,BR
152,Alexandria,31.2156,29.9553,71.56,83,6.91,0,1635470618,EG
186,Monterrey,25.6667,-100.3167,78.21,25,2.01,0,1635470466,MX
192,Zhaoqing,23.0512,112.4597,75.52,66,4.36,0,1635470670,CN
195,Xiamen,24.4798,118.0819,76.24,60,6.71,0,1635470674,CN
307,Yunfu,22.9306,112.0373,75.02,70,3.29,0,1635470823,CN
310,Dubai,25.2582,55.3047,78.73,69,6.91,0,1635470527,AE
405,Asunción,-25.3007,-57.6359,74.64,64,2.30,0,1635470715,PY
482,Porto Alegre,-30.0331,-51.2300,70.27,83,10.00,0,1635471002,BR
488,Auckland,-36.8667,174.7667,70.30,70,8.99,0,1635470931,NZ
501,Muscat,23.6139,58.5922,75.22,62,4.99,0,1635471088,OM
507,Sharjah,25.3573,55.4033,78.78,71,4.61,0,1635471010,AE
530,Montevideo,-34.8335,-56.1674,73.11,53,8.05,0,1635471117,UY
580,Ahvāz,31.3203,48.6693,71.55,28,2.30,0,1635471195,IR
583,Medina,24.4686,39.6142,75.63,16,0.00,0,1635471199,SA
597,Zhuji,29.7188,120.2423,70.90,70,4.43,0,1635471218,CN

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [52]:
hotel_df=idealCity
hotel_df['Hotel Name']=''
hotel_df

,City,Latitude,Longitude,Max_Temp,Humidity,Wind_Speed,Cloudiness,Date,Country,Hotel Name
40,Hyderābād,25.3924,68.3737,76.37,28,3.96,0,1635470473,PK,
139,Belo Horizonte,-19.9208,-43.9378,74.75,50,6.91,0,1635470370,BR,
152,Alexandria,31.2156,29.9553,71.56,83,6.91,0,1635470618,EG,
186,Monterrey,25.6667,-100.3167,78.21,25,2.01,0,1635470466,MX,
192,Zhaoqing,23.0512,112.4597,75.52,66,4.36,0,1635470670,CN,
195,Xiamen,24.4798,118.0819,76.24,60,6.71,0,1635470674,CN,
307,Yunfu,22.9306,112.0373,75.02,70,3.29,0,1635470823,CN,
310,Dubai,25.2582,55.3047,78.73,69,6.91,0,1635470527,AE,
405,Asunción,-25.3007,-57.6359,74.64,64,2.30,0,1635470715,PY,
482,Porto Alegre,-30.0331,-51.2300,70.27,83,10.00,0,1635471002,BR,
488,Auckland,-36.8667,174.7667,70.30,70,8.99,0,1635470931,NZ,
501,Muscat,23.6139,58.5922,75.22,62,4.99,0,1635471088,OM,
507,Sharjah,25.3573,55.4033,78.78,71,4.61,0,1635471010,AE,
530,Montevideo,-34.8335,-56.1674,73.11,53,8.05,0,1635471117,UY,
580,Ahvāz,31.3203,48.6693,71.55,28,2.30,0,1635471195,IR,
583,Medina,24.4686,39.6142,75.63,16,0.00,0,1635471199,SA,
597,Zhuji,29.7188,120.2423,70.90,70,4.43,0,1635471218,CN,

In [60]:
for index,row in hotel_df.iterrows():
    try:
#         url='https://maps.googleapis.com/maps/api/place/nearbysearch/json'
#         params={'keyword':'restaurant','radius':5000,'key':g_key}
        
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : "AIzaSyBdw_vDcecNQnk7TQkWKDIO33-dfeYaPiM"}       
        lat = row['Latitude']
        lng = row['Longitude']
        params['location'] = f"{lat}, {lng}"
        response = requests.get(base_url,params=params)   
        get_hotel = response.json()
        hotel_df.loc[index, "Hotel Name"] = get_hotel["results"][0]["name"]
        
    except IndexError:        
        hotel_df.loc[index, "Hotel Name"] = "Not Found"
hotel_df

,City,Latitude,Longitude,Max_Temp,Humidity,Wind_Speed,Cloudiness,Date,Country,Hotel Name
40,Hyderābād,25.3924,68.3737,76.37,28,3.96,0,1635470473,PK,Not Found
139,Belo Horizonte,-19.9208,-43.9378,74.75,50,6.91,0,1635470370,BR,Not Found
152,Alexandria,31.2156,29.9553,71.56,83,6.91,0,1635470618,EG,Not Found
186,Monterrey,25.6667,-100.3167,78.21,25,2.01,0,1635470466,MX,Not Found
192,Zhaoqing,23.0512,112.4597,75.52,66,4.36,0,1635470670,CN,Not Found
195,Xiamen,24.4798,118.0819,76.24,60,6.71,0,1635470674,CN,Not Found
307,Yunfu,22.9306,112.0373,75.02,70,3.29,0,1635470823,CN,Not Found
310,Dubai,25.2582,55.3047,78.73,69,6.91,0,1635470527,AE,Not Found
405,Asunción,-25.3007,-57.6359,74.64,64,2.30,0,1635470715,PY,Not Found
482,Porto Alegre,-30.0331,-51.2300,70.27,83,10.00,0,1635471002,BR,Not Found
488,Auckland,-36.8667,174.7667,70.30,70,8.99,0,1635470931,NZ,Not Found
501,Muscat,23.6139,58.5922,75.22,62,4.99,0,1635471088,OM,Not Found
507,Sharjah,25.3573,55.4033,78.78,71,4.61,0,1635471010,AE,Not Found
530,Montevideo,-34.8335,-56.1674,73.11,53,8.05,0,1635471117,UY,Not Found
580,Ahvāz,31.3203,48.6693,71.55,28,2.30,0,1635471195,IR,Not Found
583,Medina,24.4686,39.6142,75.63,16,0.00,0,1635471199,SA,Not Found
597,Zhuji,29.7188,120.2423,70.90,70,4.43,0,1635471218,CN,Not Found

In [61]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [57]:
# Add marker layer ontop of heat map
markers=gmaps.marker_layer(locations,info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))